stages:
- build
- publish

before_script:
- npm install

build:
  stage: build
  image: node:14
  only:
  - master
  - develop
  script:
  - npm run lint
  - npm run build
  - npm run test -- --collect-coverage --collectCoverageFrom=src/**/*.ts
  coverage: /All\sfiles.*?\s+(\d+.\d+)/


publish:
  stage: publish
  image: node:14
  only:
  - tags
  script:
  - npm run lint
  - npm run build
  - npm run test -- --collect-coverage --collectCoverageFrom=src/**/*.ts
  - npm --no-git-tag-version version ${CI_COMMIT_TAG}
  - npm publish --access public
  variables:
    NPM_TOKEN: ${NPM_TOKEN}
