stages:
- test
- build
- publish

build:
  stage: build
  image: node:14
  only:
  - master
  - develop
  script:
  - npm ci
  - npx eslint --format gitlab "src/**/*.ts"
  - npx tsc
  - npx jest --ci --reporters=default --reporters=jest-junit --collect-coverage
  coverage: /Lines\s*:\s*(\d+.?\d*)%/
  variables:
    ESLINT_CODE_QUALITY_REPORT: codequality.json
  artifacts:
    when: always
    paths:
      - coverage
    reports:
      junit: junit.xml
      codequality: codequality.json

publish:
  stage: publish
  image: node:14
  only:
  - tags
  script:
  - npm ci
  - npm run lint -- --format gitlab
  - npm run build
  - npm run test -- --collect-coverage --collectCoverageFrom=src/**/*.ts
  - npm --no-git-tag-version version ${CI_COMMIT_TAG}
  - npm publish --access public
  variables:
    NPM_TOKEN: ${NPM_TOKEN}
