stages:
- test
- build
- publish
- pages

build:
  stage: build
  image: node:14
  only:
  - master
  - develop
  - merge_requests
  script:
  - npm ci
  - npx eslint --format gitlab "src/**/*.ts"
  - npx tsc
  - npx jest --ci --reporters=default --reporters=jest-junit --collect-coverage
  coverage: /Lines\s*:\s*(\d+.?\d*)%/
  variables:
    ESLINT_CODE_QUALITY_REPORT: codequality.json
  artifacts:
    when: always
    paths:
      - coverage
    reports:
      junit: junit.xml
      codequality: codequality.json

publish:
  stage: publish
  image: node:14
  only:
  - tags
  script:
  - npm ci
  - npx eslint --format gitlab "src/**/*.ts"
  - npx tsc
  - npx jest --ci --reporters=default --reporters=jest-junit --collect-coverage
  - npm --no-git-tag-version version ${CI_COMMIT_TAG}
  - npm publish --access public
  variables:
    NPM_TOKEN: ${NPM_TOKEN}
    ESLINT_CODE_QUALITY_REPORT: codequality.json
  artifacts:
    when: always
    paths:
      - coverage
    reports:
      junit: junit.xml
      codequality: codequality.json

# This file is a template, and might need editing before it works on your project.
# Full project: https://gitlab.com/pages/plain-html
pages:
  stage: pages
  image: node:14
  script:
    - npm ci
    - npm --no-git-tag-version version ${CI_COMMIT_TAG}
    - npx typedoc --tsconfig ./tsconfig.json
  artifacts:
    paths:
      - public
  only:
    - tags
